#!/bin/bash

echo "🔍 ClipboardManager Paste Debug Test"
echo "======================================"
echo ""
echo "Instructions:"
echo "1. Install ClipboardManager from the DMG (drag to Applications)"
echo "2. Launch ClipboardManager"
echo "3. Copy some text (Cmd+C)"
echo "4. Press your global hotkey to open ClipboardManager"
echo "5. Try pressing Enter to paste"
echo "6. Check Console.app or run this command to see debug logs:"
echo ""
echo "   log stream --predicate 'subsystem == \"com.yourcompany.clipboardmanager\"' --level debug"
echo ""
echo "Or monitor all ClipboardManager related logs:"
echo ""
echo "   log stream --process ClipboardManager --level debug"
echo ""
echo "Key things to watch for in the logs:"
echo "  - 'Starting paste operation for item:'"
echo "  - 'Accessibility permission check:'"
echo "  - 'Performing programmatic paste for:'"
echo "  - 'PasteHelper paste operation started'"
echo "  - 'PasteHelper paste operation completed'"
echo ""
echo "Common issues to check:"
echo "  - Accessibility permissions in System Preferences"
echo "  - Active application can receive paste events"
echo "  - ClipboardManager has focus when Enter is pressed"
echo ""
