#!/bin/bash

# Test script for sidebar keyboard shortcut fix
echo "⌨️  Testing Sidebar Keyboard Shortcut Fix"
echo "======================================="

cd /Users/lawrencegoeseels/Documents/AI/ClipboardManager

echo "🎯 Problem identified:"
echo "- Sidebar required double press of key command after first use"
echo "- No global keyboard shortcut was implemented for sidebar toggle"
echo "- GlobalShortcutsManager only handled search and clipboard history"
echo ""
echo "✅ Solution implemented:"
echo "- Added Cmd+Shift+B keyboard shortcut for sidebar toggle"
echo "- Added toggleSidebar notification handling"
echo "- Added debug logging to track sidebar state changes"
echo ""
echo "🧪 Test instructions:"
echo "1. Launch the app"
echo "2. Test button click: Click folder icon → sidebar should toggle"
echo "3. Test keyboard shortcut: Press Cmd+Shift+B → sidebar should toggle"
echo "4. Both methods should work consistently without double press"
echo ""
echo "🔍 Debug output to watch for:"
echo "- '🔄 Toggling sidebar: false → true' (button click)"
echo "- '🔄 Toggling sidebar via keyboard shortcut: true → false' (keyboard)"
echo ""
echo "⌨️  Available keyboard shortcuts:"
echo "- Cmd+Shift+V: Show clipboard history"
echo "- Cmd+Shift+F: Show search"
echo "- Cmd+Shift+B: Toggle sidebar (NEW)"
echo "- Cmd+Option+1-9: Paste specific item"
echo ""
echo "✅ Expected behavior:"
echo "- Single press should toggle sidebar both ways"
echo "- No more double press requirement"
echo "- Consistent behavior after first use"
echo ""
echo "🚀 Starting app for testing..."
./.build/arm64-apple-macosx/debug/ClipboardManager
